version: "3"
services:
  lab-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "lab2021_app"
    ports:
      - "8080:8080"
    depends_on:
      - lab-db

  lab-db:
    image: "postgres"
    container_name: "lab2021_balloonshop"
    environment:
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=lab123
      - POSTGRES_DB=balloon-shop
    ports:
      - "5432:5432"